from __future__ import annotations

from collections import Counter
from typing import Any, Literal

from pydantic import BaseModel, Field


POLICY_COVERAGE_SCHEMA_VERSION = "groundrecall.policy_coverage.v1"

PolicyCoverageStatus = Literal["covered", "partial", "intentionally_ungated", "future"]
PolicyCoverageSurface = Literal["cli", "mcp", "python_api", "derived_projection", "future"]


class PolicyCoverageEntry(BaseModel):
    route_id: str
    surface: PolicyCoverageSurface
    operation: str
    decision_point: str
    status: PolicyCoverageStatus
    durable_memory_change: bool = False
    read_or_export_effect: bool = False
    enforcement: list[str] = Field(default_factory=list)
    audit: list[str] = Field(default_factory=list)
    tests: list[str] = Field(default_factory=list)
    caveat: str = ""


POLICY_COVERAGE_ENTRIES: tuple[PolicyCoverageEntry, ...] = (
    PolicyCoverageEntry(
        route_id="mcp.inspect_store",
        surface="mcp",
        operation="inspect_store",
        decision_point="read",
        status="covered",
        read_or_export_effect=True,
        enforcement=["optional policy_config denies/hard-gates before store inspection"],
        audit=["blocked MCP read returns structured policy decision; no durable audit log for read-only denial"],
        tests=["tests/test_mcp.py"],
        caveat="Read-only MCP denials are returned to the caller rather than written as durable audit events.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.query_memory",
        surface="mcp",
        operation="query_memory",
        decision_point="query",
        status="covered",
        read_or_export_effect=True,
        enforcement=["optional policy_config denies/hard-gates before query execution"],
        audit=["blocked MCP query returns structured policy decision; no durable audit log for read-only denial"],
        tests=["tests/test_mcp.py"],
        caveat="Read-only MCP denials are returned to the caller rather than written as durable audit events.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.search_index",
        surface="mcp",
        operation="search_index",
        decision_point="query",
        status="covered",
        read_or_export_effect=True,
        enforcement=["optional policy_config denies/hard-gates before search execution"],
        audit=["blocked MCP search returns structured policy decision; no durable audit log for read-only denial"],
        tests=["tests/test_mcp.py"],
        caveat="Read-only MCP denials are returned to the caller rather than written as durable audit events.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.export_bundle",
        surface="mcp",
        operation="export_bundle",
        decision_point="export",
        status="covered",
        read_or_export_effect=True,
        enforcement=["optional policy_config denies/hard-gates before export side effects"],
        audit=["blocked MCP export returns structured policy decision"],
        tests=["tests/test_mcp.py", "tests/test_export_guardrails.py"],
        caveat="Durable audit output for canonical export remains manifest/provenance metadata rather than a separate append-only audit log.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.evaluate_policy",
        surface="mcp",
        operation="evaluate_policy",
        decision_point="read",
        status="intentionally_ungated",
        enforcement=["evaluates a bounded request against a supplied policy config"],
        audit=["no durable memory change"],
        tests=["tests/test_mcp.py", "tests/test_policy_plugins.py"],
        caveat="The route is policy introspection, not a protected memory mutation.",
    ),
    PolicyCoverageEntry(
        route_id="cli.promote",
        surface="cli",
        operation="promote_import_to_store",
        decision_point="promote",
        status="covered",
        durable_memory_change=True,
        enforcement=["--policy-plugins denies/hard-gates before canonical store writes"],
        audit=["soft decisions recorded in snapshot metadata; hard-gates return structured error payload without writes"],
        tests=["tests/test_groundrecall_promotion.py"],
        caveat="No standalone durable audit log is written for blocked direct promotion outside the returned error payload.",
    ),
    PolicyCoverageEntry(
        route_id="cli.relation_review.apply",
        surface="cli",
        operation="apply_relation_review_batch",
        decision_point="review",
        status="covered",
        durable_memory_change=True,
        enforcement=["--policy-plugins preflight blocks deny/hard_gate before relation or candidate writes"],
        audit=["soft decisions recorded with applied rows; hard-gates return structured error payload without writes"],
        tests=["tests/test_relation_review.py"],
        caveat="No standalone durable audit log is written for blocked direct relation-review application outside the returned error payload.",
    ),
    PolicyCoverageEntry(
        route_id="cli.review.quorum",
        surface="cli",
        operation="evaluate_review_quorum",
        decision_point="review",
        status="partial",
        enforcement=["minimum approvals, reviewer-role requirements, duplicate-principal checks, and independence checks are evaluated before high-risk promotion callers can rely on receipts"],
        audit=["result identifies missing roles, duplicate reviewers, non-independent reviewers, dissent, and invalidated content hashes"],
        tests=["tests/test_institutional_review.py"],
        caveat="The quorum evaluator is implemented; policy-plugin preflight and automatic blocking inside every promotion path remain follow-up wiring.",
    ),
    PolicyCoverageEntry(
        route_id="cli.review.feedback_bundle",
        surface="cli",
        operation="build_feedback_bundle",
        decision_point="propose",
        status="partial",
        read_or_export_effect=True,
        enforcement=["feedback records preserve producer/receiver adjudications as separate assertions", "bundle content hash and HMAC signature protect the exported payload"],
        audit=["feedback bundle includes origin, target, key ID, content hash, and related receipt/adjudication IDs"],
        tests=["tests/test_institutional_review.py"],
        caveat="Feedback records and signing are implemented; policy-plugin preflight, direct feedback-bundle import, and durable federation audit remain future work.",
    ),
    PolicyCoverageEntry(
        route_id="cli.contradictions.adjudicate",
        surface="cli",
        operation="adjudicate_contradiction_case",
        decision_point="adjudicate",
        status="covered",
        durable_memory_change=True,
        enforcement=["--policy-plugins blocks deny/hard_gate before adjudication and case writes"],
        audit=["soft decisions recorded in adjudication and case metadata; hard-gates return structured error payload without writes"],
        tests=["tests/test_contradictions.py"],
        caveat="No standalone durable audit log is written for blocked direct adjudication outside the returned error payload.",
    ),
    PolicyCoverageEntry(
        route_id="cli.export.canonical_public",
        surface="cli",
        operation="export_canonical_bundle",
        decision_point="export",
        status="covered",
        read_or_export_effect=True,
        enforcement=["--policy-plugins denies/hard-gates before output directories are created", "public export guardrails filter release levels and sensitive records"],
        audit=["policy decision recorded in export manifest and provenance manifest for completed exports"],
        tests=["tests/test_export_guardrails.py", "tests/test_groundrecall_export.py"],
        caveat="Blocked direct public export does not yet append a separate durable audit log.",
    ),
    PolicyCoverageEntry(
        route_id="cli.federation.export",
        surface="cli",
        operation="export_federation_bundle",
        decision_point="federate_export",
        status="covered",
        read_or_export_effect=True,
        enforcement=["local federation policy and generic policy-plugin checks block unauthorized export"],
        audit=["federation audit log records local-policy and policy-plugin export decisions when audit path is supplied"],
        tests=["tests/test_federation.py"],
        caveat="Audit durability depends on callers supplying an audit log path.",
    ),
    PolicyCoverageEntry(
        route_id="cli.federation.import_quarantine",
        surface="cli",
        operation="import_federation_bundle_to_quarantine",
        decision_point="federate_import",
        status="covered",
        durable_memory_change=True,
        enforcement=["signature/content-hash verification, local federation policy, and generic policy-plugin checks block unauthorized quarantine import"],
        audit=["federation audit log records quarantine/rejection decisions when audit path is supplied"],
        tests=["tests/test_federation.py"],
        caveat="Audit durability depends on callers supplying an audit log path.",
    ),
    PolicyCoverageEntry(
        route_id="cli.federation.promote_quarantine",
        surface="cli",
        operation="promote_quarantine_bundle",
        decision_point="promote",
        status="covered",
        durable_memory_change=True,
        enforcement=["local federation policy, conflict planning, and generic policy-plugin checks block unauthorized promotion"],
        audit=["federation audit log records promotion/rejection decisions when audit path is supplied"],
        tests=["tests/test_federation.py"],
        caveat="Audit durability depends on callers supplying an audit log path.",
    ),
    PolicyCoverageEntry(
        route_id="cli.graph_augment.write_candidates",
        surface="cli",
        operation="augment_store_relations_from_claims",
        decision_point="propose",
        status="covered",
        durable_memory_change=True,
        enforcement=["dry-run by default", "sensitive/private/no-export records are screened before candidate generation", "--policy-plugins blocks deny/hard_gate before candidate relation or review-candidate writes"],
        audit=["soft decisions recorded in write_summary", "--audit-log writes JSONL graph policy preflight events for allowed and blocked policy decisions"],
        tests=["tests/test_graph_augment.py", "tests/test_graph_maintenance.py", "tests/test_export_guardrails.py"],
        caveat="Durable audit output depends on callers supplying an audit log path.",
    ),
    PolicyCoverageEntry(
        route_id="cli.graph_maintenance.apply",
        surface="cli",
        operation="run_graph_maintenance_slice",
        decision_point="propose",
        status="covered",
        durable_memory_change=True,
        enforcement=["dry-run unless --apply is supplied", "bounded profiles, state files, locks, stale-lock recovery", "delegates sensitive-record screening and policy-plugin write gating to graph backfill"],
        audit=["soft decisions recorded in write_summary and maintenance run history when state advances", "--audit-log writes JSONL graph policy preflight events for allowed and blocked policy decisions"],
        tests=["tests/test_graph_maintenance.py"],
        caveat="Durable audit output depends on callers supplying an audit log path.",
    ),
    PolicyCoverageEntry(
        route_id="cli.import",
        surface="cli",
        operation="run_groundrecall_import",
        decision_point="propose",
        status="covered",
        durable_memory_change=True,
        enforcement=["--policy-plugins denies/hard-gates before import output directories or proposal files are written", "imports create review candidates/proposals rather than canonical truth"],
        audit=["soft decisions recorded in import manifest", "--audit-log writes JSONL import policy preflight events for allowed and blocked policy decisions"],
        tests=["tests/test_groundrecall_import.py", "tests/test_groundrecall_source_adapters.py"],
        caveat="Durable audit output depends on callers supplying an audit log path; canonical promotion remains separately gated.",
    ),
    PolicyCoverageEntry(
        route_id="cli.index.rebuild",
        surface="derived_projection",
        operation="build_search_index",
        decision_point="read",
        status="intentionally_ungated",
        read_or_export_effect=True,
        enforcement=["index is a rebuildable local projection over existing store state"],
        audit=["no durable memory change"],
        tests=["tests/test_search_index.py"],
        caveat="Index rebuilding should remain constrained by filesystem access and release-filtered query/export surfaces.",
    ),
    PolicyCoverageEntry(
        route_id="cli.query",
        surface="cli",
        operation="query_store",
        decision_point="query",
        status="covered",
        read_or_export_effect=True,
        enforcement=["--policy-plugins denies/hard-gates before store access", "query output carries provenance, contradiction, supersession, release, graph, and confidence context where available"],
        audit=["soft decisions are attached to CLI query output; blocked direct CLI reads return structured policy payloads"],
        tests=["tests/test_groundrecall_query.py", "tests/test_groundrecall_namespace.py"],
        caveat="Direct CLI read denials are returned to the caller rather than written as durable audit events.",
    ),
    PolicyCoverageEntry(
        route_id="cli.erasure.plan",
        surface="cli",
        operation="exceptional_erasure_plan",
        decision_point="delete",
        status="covered",
        enforcement=["dry-run only; creates no destructive changes", "records requested authority and reason class", "reports affected records and rebuildable projections before execution exists"],
        audit=["plan includes minimal tombstone payload with affected counts, content hashes, and origin hashes"],
        tests=["tests/test_erasure.py"],
        caveat="Planning is implemented; destructive erasure execution and re-import blocking remain future work.",
    ),
    PolicyCoverageEntry(
        route_id="cli.custody.orphans",
        surface="cli",
        operation="orphan_stewardship_report",
        decision_point="query",
        status="covered",
        read_or_export_effect=True,
        enforcement=["deterministic read-only report over explicit stewardship records", "does not infer stewardship from raw activity volume"],
        audit=["report lists subject IDs, scope IDs, release levels, current status, and orphan reason"],
        tests=["tests/test_institutional_custody.py"],
        caveat="Read policy plugins are not wired directly into the report command yet; callers should run it in scoped stores or filtered contexts.",
    ),
    PolicyCoverageEntry(
        route_id="cli.custody.departure_plan",
        surface="cli",
        operation="plan_tenancy_departure",
        decision_point="act",
        status="covered",
        enforcement=["dry-run only; creates no destructive changes", "separates private personal records from group-owned reviewed records", "requires successor/orphan handling for active stewardship"],
        audit=["plan carries stable ID, active stewardship IDs, custody event IDs, handoff rows, retention rows, and warnings"],
        tests=["tests/test_institutional_custody.py"],
        caveat="Apply commands are intentionally absent until dry-run planning is further reviewed.",
    ),
    PolicyCoverageEntry(
        route_id="cli.custody.retirement_plan",
        surface="cli",
        operation="plan_instance_retirement",
        decision_point="act",
        status="covered",
        enforcement=["dry-run only; creates no destructive changes", "reports trust keys, subscriptions, catalogs, pending contributions, stewardship, canonical counts, quarantine, and backups"],
        audit=["plan lists required retirement actions and warnings for unresolved active keys, pending contributions, missing replacement, and stewardship handoff"],
        tests=["tests/test_institutional_custody.py"],
        caveat="Key revocation and subscription shutdown remain separate authorized operations.",
    ),
    PolicyCoverageEntry(
        route_id="cli.views.orientation",
        surface="cli",
        operation="scope_orientation_pack",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["release-cap filtering limits visible scope records and dependent context", "pack exposes incomplete basis instead of fabricating unavailable evidence"],
        audit=["view carries schema version, scope ID, release cap, stale items, contradiction state, steward roles, and incomplete-basis labels"],
        tests=["tests/test_institutional_views.py"],
        caveat="Policy-plugin preflight and post-render filtering remain follow-up wiring.",
    ),
    PolicyCoverageEntry(
        route_id="cli.views.impact",
        surface="cli",
        operation="change_impact_report",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["release-cap filtering limits dependents", "contradiction and confidence state remain explicit"],
        audit=["report includes subject, direct dependents, contradiction state, confidence state, and incomplete-basis labels"],
        tests=["tests/test_institutional_views.py"],
        caveat="Policy-plugin preflight and deeper graph dependency expansion remain follow-up wiring.",
    ),
    PolicyCoverageEntry(
        route_id="cli.views.governance",
        surface="cli",
        operation="governance_health_report",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["release-cap filtering limits governance findings", "uses explicit stewardship and review state rather than activity ranking"],
        audit=["report counts unowned scopes/records, stale high-impact records, unresolved conflicts, incomplete provenance, and unacknowledged subscriptions"],
        tests=["tests/test_institutional_views.py"],
        caveat="Policy drift detection is limited to unacknowledged subscriptions in this first slice.",
    ),
    PolicyCoverageEntry(
        route_id="cli.views.stewardship",
        surface="cli",
        operation="stewardship_view",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["view lists explicit stewardship records only", "raw activity rankings and inferred familiarity are suppressed"],
        audit=["view labels its basis and unavailable evidence"],
        tests=["tests/test_institutional_views.py"],
        caveat="Policy-plugin preflight and privacy-specific redaction beyond release cap remain follow-up wiring.",
    ),
    PolicyCoverageEntry(
        route_id="cli.release.pack",
        surface="cli",
        operation="build_release_pack",
        decision_point="publish",
        status="partial",
        read_or_export_effect=True,
        enforcement=["missing or incompatible licenses hard-gate pack generation", "missing attribution hard-gates pack generation", "manifest content hash and HMAC signature protect deterministic record payloads", "withdrawal notices can block re-entry by pack ID"],
        audit=["manifest records license IDs, attribution count, redaction policy IDs, superseded packs, review receipts, policy ID, key ID, content hash, and signature"],
        tests=["tests/test_institutional_release.py"],
        caveat="ClaimWright policy-plugin preflight and publication-gatekeeper review are not wired directly into the command yet.",
    ),
    PolicyCoverageEntry(
        route_id="cli.release.withdraw",
        surface="cli",
        operation="build_withdrawal_notice",
        decision_point="supersede",
        status="partial",
        read_or_export_effect=True,
        enforcement=["withdrawal notice is signed and content-hashed", "notice explicitly distinguishes withdrawal from erasure and preserves historical audit state"],
        audit=["notice records pack ID, reason, authority, withdrawal time, superseding pack, content hash, key ID, and signature"],
        tests=["tests/test_institutional_release.py"],
        caveat="Distributed withdrawal propagation and direct policy-plugin review remain follow-up work.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.prior_work_review",
        surface="mcp",
        operation="prior_work_search",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["optional policy_config can block before store access", "release cap limits visible prior-work candidates"],
        audit=["MCP response includes policy decision when policy_config is supplied"],
        tests=["tests/test_mcp.py"],
        caveat="MCP policy checks remain caller-supplied rather than mandatory server configuration.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.catalog_discovery",
        surface="mcp",
        operation="query_federation_catalog",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["optional policy_config can block before catalog read", "catalog entries expose stable discovery metadata rather than canonical records"],
        audit=["MCP response includes policy decision when policy_config is supplied"],
        tests=["tests/test_mcp.py"],
        caveat="Catalog signature verification is performed by catalog import/export paths; this query tool assumes a selected local catalog path.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.subscription_status",
        surface="mcp",
        operation="load_subscription",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["optional policy_config can block before subscription status read", "response exposes cursor and filters without importing or acknowledging changes"],
        audit=["MCP response includes policy decision when policy_config is supplied"],
        tests=["tests/test_mcp.py"],
        caveat="Subscription status is local file metadata; durable access audit remains future work.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.impact_report",
        surface="mcp",
        operation="change_impact_report",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["optional policy_config can block before store access", "release cap limits rendered impact report"],
        audit=["MCP response includes policy decision when policy_config is supplied"],
        tests=["tests/test_mcp.py"],
        caveat="Post-render policy filtering remains follow-up work.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.stewardship_orphans",
        surface="mcp",
        operation="stewardship_view_and_orphan_report",
        decision_point="query",
        status="partial",
        read_or_export_effect=True,
        enforcement=["optional policy_config can block before store access", "stewardship view suppresses activity ranking"],
        audit=["MCP response includes policy decision when policy_config is supplied"],
        tests=["tests/test_mcp.py"],
        caveat="Release-cap filtering is applied to stewardship view; orphan report currently returns explicit IDs from the scoped store.",
    ),
    PolicyCoverageEntry(
        route_id="mcp.propose_contribution",
        surface="mcp",
        operation="draft_contribution_proposal",
        decision_point="propose",
        status="partial",
        enforcement=["optional policy_config can block before proposal generation", "tool performs no canonical store writes"],
        audit=["response labels writes_performed=false and includes authority notice"],
        tests=["tests/test_mcp.py"],
        caveat="Canonical contribution creation remains a separate repository operation with explicit policy-gated writes.",
    ),
    PolicyCoverageEntry(
        route_id="python_api.custody.record_event",
        surface="python_api",
        operation="record_custody_event",
        decision_point="act",
        status="covered",
        durable_memory_change=True,
        enforcement=["blocks custody event release broadening relative to the subject record", "policy_provider deny/hard_gate blocks before append-only custody-event write", "preserves custody event as append-only audit state"],
        audit=["custody event records event kind, authority, previous/new custodian, rationale, timestamp, and release level", "blocked policy decisions are returned in CustodyPolicyError without writes"],
        tests=["tests/test_institutional_custody.py"],
        caveat="Explicit role/authority validation remains follow-up wiring beyond policy-provider preflight.",
    ),
    PolicyCoverageEntry(
        route_id="cli.catalog.export",
        surface="cli",
        operation="build_signed_federation_catalog",
        decision_point="federate_export",
        status="covered",
        read_or_export_effect=True,
        enforcement=["policy-plugin preflight blocks deny/hard_gate before catalog output", "release-filtered scope metadata and detail levels limit disclosure"],
        audit=["policy decision is retained in catalog metadata; durable federation audit log remains optional"],
        tests=["tests/test_catalog.py"],
        caveat="Catalog transport and automated protected-topic inference evaluation are not implemented.",
    ),
    PolicyCoverageEntry(
        route_id="cli.catalog.import",
        surface="cli",
        operation="import_federation_catalog_to_quarantine",
        decision_point="federate_import",
        status="covered",
        durable_memory_change=True,
        enforcement=["signature/content-hash verification", "receiver-side release and producer-instance caps", "policy-plugin preflight before quarantine write"],
        audit=["quarantine result records cap and policy decision metadata"],
        tests=["tests/test_catalog.py"],
        caveat="Catalog import remains quarantine metadata; it does not promote knowledge into the canonical store.",
    ),
    PolicyCoverageEntry(
        route_id="cli.changes.export",
        surface="cli",
        operation="build_incremental_change_bundle",
        decision_point="federate_export",
        status="covered",
        read_or_export_effect=True,
        enforcement=["policy-plugin preflight blocks deny/hard_gate", "scope/release/change filters and producer cursor bound the bundle", "deterministic content hash and signature protect the payload"],
        audit=["policy decision is embedded in the signed bundle metadata"],
        tests=["tests/test_change_feed.py"],
        caveat="File transport is implemented; network delivery and durable federation audit remain future work.",
    ),
    PolicyCoverageEntry(
        route_id="cli.changes.import",
        surface="cli",
        operation="import_incremental_change_bundle_to_quarantine",
        decision_point="federate_import",
        status="covered",
        durable_memory_change=True,
        enforcement=["signature/content-hash verification", "subscription identity check", "policy-plugin preflight before idempotent quarantine write"],
        audit=["quarantine result records replay and policy metadata"],
        tests=["tests/test_change_feed.py"],
        caveat="Import does not promote events into canonical records.",
    ),
    PolicyCoverageEntry(
        route_id="cli.changes.ack",
        surface="cli",
        operation="acknowledge_change_bundle",
        decision_point="act",
        status="covered",
        durable_memory_change=True,
        enforcement=["producer/subscription identity and cursor continuity are checked", "optional signature verification can be required before advancing"],
        audit=["cursor advancement is durable in the receiver-local subscription file"],
        tests=["tests/test_change_feed.py"],
        caveat="Explicit policy-plugin review for acknowledgement and append-only audit events remain follow-up work.",
    ),
    PolicyCoverageEntry(
        route_id="python_api.institutional.transition_contribution",
        surface="python_api",
        operation="transition_contribution",
        decision_point="review",
        status="covered",
        durable_memory_change=True,
        enforcement=["policy_provider deny/hard_gate blocks before contribution or receipt writes", "contribution state transitions validate lifecycle order and require a reviewer/rationale"],
        audit=["append-only review receipt is persisted with reviewed content hashes and policy ID"],
        tests=["tests/test_institutional_write.py", "tests/test_institutional_federation.py"],
        caveat="The helper is a Python API surface; direct low-level store methods remain available for trusted internal callers.",
    ),
    PolicyCoverageEntry(
        route_id="python_api.institutional.save_records",
        surface="python_api",
        operation="save_institutional_records",
        decision_point="propose",
        status="covered",
        durable_memory_change=True,
        enforcement=["policy_provider deny/hard_gate blocks before scope, work, decision, contribution, stewardship, custody-event, or contribution-review receipt writes"],
        audit=["write result returns policy decision, record kind, record ID, and written IDs"],
        tests=["tests/test_institutional_write.py", "tests/test_institutional_federation.py"],
        caveat="The helper centralizes policy-aware institutional writes, but it is not a complete role/authority system.",
    ),
    PolicyCoverageEntry(
        route_id="future.exceptional_erasure",
        surface="future",
        operation="exceptional_erasure",
        decision_point="delete",
        status="future",
        durable_memory_change=True,
        enforcement=["planned destructive-operation policy gate"],
        audit=["planned minimal non-sensitive tombstone and denied-write audit"],
        tests=[],
        caveat="No exceptional-erasure execution path exists yet.",
    ),
)


def build_policy_coverage_report(*, compact: bool = False) -> dict[str, Any]:
    entries = [entry.model_dump(mode="json") for entry in POLICY_COVERAGE_ENTRIES]
    status_counts = Counter(entry["status"] for entry in entries)
    surface_counts = Counter(entry["surface"] for entry in entries)
    durable_entries = [entry for entry in entries if entry["durable_memory_change"]]
    durable_status_counts = Counter(entry["status"] for entry in durable_entries)
    partial_or_future = [entry for entry in entries if entry["status"] in {"partial", "future"}]
    payload: dict[str, Any] = {
        "schema_version": POLICY_COVERAGE_SCHEMA_VERSION,
        "summary": {
            "route_count": len(entries),
            "covered_route_count": status_counts.get("covered", 0),
            "partial_route_count": status_counts.get("partial", 0),
            "intentionally_ungated_route_count": status_counts.get("intentionally_ungated", 0),
            "future_route_count": status_counts.get("future", 0),
            "durable_mutation_route_count": len(durable_entries),
            "covered_durable_mutation_route_count": durable_status_counts.get("covered", 0),
            "partial_durable_mutation_route_count": durable_status_counts.get("partial", 0),
            "future_durable_mutation_route_count": durable_status_counts.get("future", 0),
            "read_or_export_route_count": sum(1 for entry in entries if entry["read_or_export_effect"]),
        },
        "status_counts": dict(sorted(status_counts.items())),
        "surface_counts": dict(sorted(surface_counts.items())),
        "open_items": [
            {
                "route_id": entry["route_id"],
                "status": entry["status"],
                "operation": entry["operation"],
                "caveat": entry["caveat"],
            }
            for entry in partial_or_future
        ],
    }
    if not compact:
        payload["routes"] = entries
    return payload
